// @generated — regenerated by build.rs from vendor/kallichore.json.
// To refresh: edit vendor/kallichore.json (or re-run `cargo build`).
// Do not edit by hand; changes will be overwritten on the next build.
#[allow(unused_imports)]
use progenitor_client::{encode_path, ClientHooks, OperationInfo, RequestBuilderExt};
#[allow(unused_imports)]
pub use progenitor_client::{ByteStream, ClientInfo, Error, ResponseValue};
#[doc = r" Types used as operation parameters and responses."]
#[allow(clippy::all)]
pub mod types {
    #[doc = r" Error types."]
    pub mod error {
        #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
        pub struct ConversionError(::std::borrow::Cow<'static, str>);
        impl ::std::error::Error for ConversionError {}
        impl ::std::fmt::Display for ConversionError {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
                ::std::fmt::Display::fmt(&self.0, f)
            }
        }
        impl ::std::fmt::Debug for ConversionError {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
                ::std::fmt::Debug::fmt(&self.0, f)
            }
        }
        impl From<&'static str> for ConversionError {
            fn from(value: &'static str) -> Self {
                Self(value.into())
            }
        }
        impl From<String> for ConversionError {
            fn from(value: String) -> Self {
                Self(value.into())
            }
        }
    }
    #[doc = "`ActiveSession`"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"argv\","]
    #[doc = "    \"busy_seconds\","]
    #[doc = "    \"connected\","]
    #[doc = "    \"continuation_prompt\","]
    #[doc = "    \"display_name\","]
    #[doc = "    \"execution_queue\","]
    #[doc = "    \"idle_seconds\","]
    #[doc = "    \"input_prompt\","]
    #[doc = "    \"interrupt_mode\","]
    #[doc = "    \"kernel_info\","]
    #[doc = "    \"language\","]
    #[doc = "    \"session_id\","]
    #[doc = "    \"session_mode\","]
    #[doc = "    \"started\","]
    #[doc = "    \"status\","]
    #[doc = "    \"username\","]
    #[doc = "    \"working_directory\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"argv\": {"]
    #[doc = "      \"description\": \"The program and command-line parameters for the session\","]
    #[doc = "      \"type\": \"array\","]
    #[doc = "      \"items\": {"]
    #[doc = "        \"type\": \"string\""]
    #[doc = "      }"]
    #[doc = "    },"]
    #[doc = "    \"busy_seconds\": {"]
    #[doc = "      \"description\": \"The number of seconds the session has been busy, or 0 if the session is idle\","]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    },"]
    #[doc = "    \"connected\": {"]
    #[doc = "      \"description\": \"Whether the session is connected to a client\","]
    #[doc = "      \"type\": \"boolean\""]
    #[doc = "    },"]
    #[doc = "    \"continuation_prompt\": {"]
    #[doc = "      \"description\": \"The text to use to prompt for input continuations\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"display_name\": {"]
    #[doc = "      \"description\": \"A human-readable name for the session\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"execution_queue\": {"]
    #[doc = "      \"$ref\": \"#/components/schemas/execution_queue\""]
    #[doc = "    },"]
    #[doc = "    \"idle_seconds\": {"]
    #[doc = "      \"description\": \"The number of seconds the session has been idle, or 0 if the session is busy\","]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    },"]
    #[doc = "    \"initial_env\": {"]
    #[doc = "      \"description\": \"The environment variables set when the session was started\","]
    #[doc = "      \"type\": \"object\","]
    #[doc = "      \"additionalProperties\": {"]
    #[doc = "        \"type\": \"string\""]
    #[doc = "      }"]
    #[doc = "    },"]
    #[doc = "    \"input_prompt\": {"]
    #[doc = "      \"description\": \"The text to use to prompt for input\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"interrupt_mode\": {"]
    #[doc = "      \"$ref\": \"#/components/schemas/interrupt_mode\""]
    #[doc = "    },"]
    #[doc = "    \"kernel_info\": {"]
    #[doc = "      \"description\": \"The kernel information, as returned by the kernel_info_request message\","]
    #[doc = "      \"type\": \"object\""]
    #[doc = "    },"]
    #[doc = "    \"language\": {"]
    #[doc = "      \"description\": \"The interpreter language\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"notebook_uri\": {"]
    #[doc = "      \"description\": \"For notebook sessions, the URI of the notebook file\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"process_id\": {"]
    #[doc = "      \"description\": \"The underlying process ID of the session, if the session is running.\","]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    },"]
    #[doc = "    \"resource_usage\": {"]
    #[doc = "      \"$ref\": \"#/components/schemas/resourceUsage\""]
    #[doc = "    },"]
    #[doc = "    \"session_id\": {"]
    #[doc = "      \"description\": \"A unique identifier for the session\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"session_mode\": {"]
    #[doc = "      \"$ref\": \"#/components/schemas/sessionMode\""]
    #[doc = "    },"]
    #[doc = "    \"socket_path\": {"]
    #[doc = "      \"description\": \"The path to the Unix domain socket used to send/receive data from the session, if applicable\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"started\": {"]
    #[doc = "      \"description\": \"An ISO 8601 timestamp of when the session was started\","]
    #[doc = "      \"type\": \"string\","]
    #[doc = "      \"format\": \"date-time\""]
    #[doc = "    },"]
    #[doc = "    \"status\": {"]
    #[doc = "      \"$ref\": \"#/components/schemas/status\""]
    #[doc = "    },"]
    #[doc = "    \"username\": {"]
    #[doc = "      \"description\": \"The username of the user who owns the session\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"working_directory\": {"]
    #[doc = "      \"description\": \"The session's current working directory\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    pub struct ActiveSession {
        #[doc = "The program and command-line parameters for the session"]
        pub argv: ::std::vec::Vec<::std::string::String>,
        #[doc = "The number of seconds the session has been busy, or 0 if the session is idle"]
        pub busy_seconds: i64,
        #[doc = "Whether the session is connected to a client"]
        pub connected: bool,
        #[doc = "The text to use to prompt for input continuations"]
        pub continuation_prompt: ::std::string::String,
        #[doc = "A human-readable name for the session"]
        pub display_name: ::std::string::String,
        pub execution_queue: ExecutionQueue,
        #[doc = "The number of seconds the session has been idle, or 0 if the session is busy"]
        pub idle_seconds: i64,
        #[doc = "The environment variables set when the session was started"]
        #[serde(
            default,
            skip_serializing_if = ":: std :: collections :: HashMap::is_empty"
        )]
        pub initial_env: ::std::collections::HashMap<::std::string::String, ::std::string::String>,
        #[doc = "The text to use to prompt for input"]
        pub input_prompt: ::std::string::String,
        pub interrupt_mode: InterruptMode,
        #[doc = "The kernel information, as returned by the kernel_info_request message"]
        pub kernel_info: ::serde_json::Map<::std::string::String, ::serde_json::Value>,
        #[doc = "The interpreter language"]
        pub language: ::std::string::String,
        #[doc = "For notebook sessions, the URI of the notebook file"]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub notebook_uri: ::std::option::Option<::std::string::String>,
        #[doc = "The underlying process ID of the session, if the session is running."]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub process_id: ::std::option::Option<i64>,
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub resource_usage: ::std::option::Option<ResourceUsage>,
        #[doc = "A unique identifier for the session"]
        pub session_id: ::std::string::String,
        pub session_mode: SessionMode,
        #[doc = "The path to the Unix domain socket used to send/receive data from the session, if applicable"]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub socket_path: ::std::option::Option<::std::string::String>,
        #[doc = "An ISO 8601 timestamp of when the session was started"]
        pub started: ::chrono::DateTime<::chrono::offset::Utc>,
        pub status: Status,
        #[doc = "The username of the user who owns the session"]
        pub username: ::std::string::String,
        #[doc = "The session's current working directory"]
        pub working_directory: ::std::string::String,
    }
    #[doc = "`ClientHeartbeat`"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"process_id\": {"]
    #[doc = "      \"description\": \"The process ID of the client sending the heartbeat\","]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    pub struct ClientHeartbeat {
        #[doc = "The process ID of the client sending the heartbeat"]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub process_id: ::std::option::Option<i64>,
    }
    impl ::std::default::Default for ClientHeartbeat {
        fn default() -> Self {
            Self {
                process_id: Default::default(),
            }
        }
    }
    #[doc = "Connection information for an existing session"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"Connection information for an existing session\","]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"control_port\","]
    #[doc = "    \"hb_port\","]
    #[doc = "    \"iopub_port\","]
    #[doc = "    \"ip\","]
    #[doc = "    \"key\","]
    #[doc = "    \"shell_port\","]
    #[doc = "    \"signature_scheme\","]
    #[doc = "    \"stdin_port\","]
    #[doc = "    \"transport\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"control_port\": {"]
    #[doc = "      \"description\": \"The port for control messages\","]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    },"]
    #[doc = "    \"hb_port\": {"]
    #[doc = "      \"description\": \"The port for heartbeat messages\","]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    },"]
    #[doc = "    \"iopub_port\": {"]
    #[doc = "      \"description\": \"The port for IOPub messages\","]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    },"]
    #[doc = "    \"ip\": {"]
    #[doc = "      \"description\": \"The IP address for the connection\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"key\": {"]
    #[doc = "      \"description\": \"The key for messages\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"shell_port\": {"]
    #[doc = "      \"description\": \"The port for shell messages\","]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    },"]
    #[doc = "    \"signature_scheme\": {"]
    #[doc = "      \"description\": \"The signature scheme for messages\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"stdin_port\": {"]
    #[doc = "      \"description\": \"The port for stdin messages\","]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    },"]
    #[doc = "    \"transport\": {"]
    #[doc = "      \"description\": \"The transport protocol\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    pub struct ConnectionInfo {
        #[doc = "The port for control messages"]
        pub control_port: i64,
        #[doc = "The port for heartbeat messages"]
        pub hb_port: i64,
        #[doc = "The port for IOPub messages"]
        pub iopub_port: i64,
        #[doc = "The IP address for the connection"]
        pub ip: ::std::string::String,
        #[doc = "The key for messages"]
        pub key: ::std::string::String,
        #[doc = "The port for shell messages"]
        pub shell_port: i64,
        #[doc = "The signature scheme for messages"]
        pub signature_scheme: ::std::string::String,
        #[doc = "The port for stdin messages"]
        pub stdin_port: i64,
        #[doc = "The transport protocol"]
        pub transport: ::std::string::String,
    }
    #[doc = "A list of environment variable actions to perform"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"A list of environment variable actions to perform\","]
    #[doc = "  \"type\": \"array\","]
    #[doc = "  \"items\": {"]
    #[doc = "    \"$ref\": \"#/components/schemas/varAction\""]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    #[serde(transparent)]
    pub struct EnvVarActions(pub ::std::vec::Vec<VarAction>);
    impl ::std::ops::Deref for EnvVarActions {
        type Target = ::std::vec::Vec<VarAction>;
        fn deref(&self) -> &::std::vec::Vec<VarAction> {
            &self.0
        }
    }
    impl ::std::convert::From<EnvVarActions> for ::std::vec::Vec<VarAction> {
        fn from(value: EnvVarActions) -> Self {
            value.0
        }
    }
    impl ::std::convert::From<::std::vec::Vec<VarAction>> for EnvVarActions {
        fn from(value: ::std::vec::Vec<VarAction>) -> Self {
            Self(value)
        }
    }
    #[doc = "`Error`"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"code\","]
    #[doc = "    \"message\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"code\": {"]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"details\": {"]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"message\": {"]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    pub struct Error {
        pub code: ::std::string::String,
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub details: ::std::option::Option<::std::string::String>,
        pub message: ::std::string::String,
    }
    #[doc = "A single output message produced during code execution"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"A single output message produced during code execution\","]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"type\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"data\": {"]
    #[doc = "      \"description\": \"MIME-keyed data, for display_data output\","]
    #[doc = "      \"type\": \"object\","]
    #[doc = "      \"additionalProperties\": {"]
    #[doc = "        \"type\": \"string\""]
    #[doc = "      }"]
    #[doc = "    },"]
    #[doc = "    \"error_message\": {"]
    #[doc = "      \"description\": \"The error message, for error output\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"error_name\": {"]
    #[doc = "      \"description\": \"The error name, for error output\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"error_traceback\": {"]
    #[doc = "      \"description\": \"The error traceback lines, for error output\","]
    #[doc = "      \"type\": \"array\","]
    #[doc = "      \"items\": {"]
    #[doc = "        \"type\": \"string\""]
    #[doc = "      }"]
    #[doc = "    },"]
    #[doc = "    \"metadata\": {"]
    #[doc = "      \"description\": \"Metadata dictionary, for display_data output\","]
    #[doc = "      \"type\": \"object\""]
    #[doc = "    },"]
    #[doc = "    \"stream_name\": {"]
    #[doc = "      \"description\": \"The stream name (stdout or stderr), for stream output\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"text\": {"]
    #[doc = "      \"description\": \"The text content, for stream output\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"type\": {"]
    #[doc = "      \"description\": \"The output message type\","]
    #[doc = "      \"type\": \"string\","]
    #[doc = "      \"enum\": ["]
    #[doc = "        \"stream\","]
    #[doc = "        \"display_data\","]
    #[doc = "        \"error\""]
    #[doc = "      ]"]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    pub struct ExecuteOutput {
        #[doc = "MIME-keyed data, for display_data output"]
        #[serde(
            default,
            skip_serializing_if = ":: std :: collections :: HashMap::is_empty"
        )]
        pub data: ::std::collections::HashMap<::std::string::String, ::std::string::String>,
        #[doc = "The error message, for error output"]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub error_message: ::std::option::Option<::std::string::String>,
        #[doc = "The error name, for error output"]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub error_name: ::std::option::Option<::std::string::String>,
        #[doc = "The error traceback lines, for error output"]
        #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
        pub error_traceback: ::std::vec::Vec<::std::string::String>,
        #[doc = "Metadata dictionary, for display_data output"]
        #[serde(default, skip_serializing_if = "::serde_json::Map::is_empty")]
        pub metadata: ::serde_json::Map<::std::string::String, ::serde_json::Value>,
        #[doc = "The stream name (stdout or stderr), for stream output"]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub stream_name: ::std::option::Option<::std::string::String>,
        #[doc = "The text content, for stream output"]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub text: ::std::option::Option<::std::string::String>,
        #[doc = "The output message type"]
        #[serde(rename = "type")]
        pub type_: ExecuteOutputType,
    }
    #[doc = "The output message type"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"The output message type\","]
    #[doc = "  \"type\": \"string\","]
    #[doc = "  \"enum\": ["]
    #[doc = "    \"stream\","]
    #[doc = "    \"display_data\","]
    #[doc = "    \"error\""]
    #[doc = "  ]"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(
        :: serde :: Deserialize,
        :: serde :: Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum ExecuteOutputType {
        #[serde(rename = "stream")]
        Stream,
        #[serde(rename = "display_data")]
        DisplayData,
        #[serde(rename = "error")]
        Error,
    }
    impl ::std::fmt::Display for ExecuteOutputType {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Stream => f.write_str("stream"),
                Self::DisplayData => f.write_str("display_data"),
                Self::Error => f.write_str("error"),
            }
        }
    }
    impl ::std::str::FromStr for ExecuteOutputType {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "stream" => Ok(Self::Stream),
                "display_data" => Ok(Self::DisplayData),
                "error" => Ok(Self::Error),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for ExecuteOutputType {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<&::std::string::String> for ExecuteOutputType {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for ExecuteOutputType {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    #[doc = "The result of executing code in a session"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"The result of executing code in a session\","]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"execution_count\","]
    #[doc = "    \"output\","]
    #[doc = "    \"status\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"data\": {"]
    #[doc = "      \"description\": \"The execution result as a MIME-keyed dictionary (from execute_result), if the execution produced a result\","]
    #[doc = "      \"type\": \"object\","]
    #[doc = "      \"additionalProperties\": {"]
    #[doc = "        \"type\": \"string\""]
    #[doc = "      }"]
    #[doc = "    },"]
    #[doc = "    \"error_message\": {"]
    #[doc = "      \"description\": \"The error message, if the execution failed\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"error_name\": {"]
    #[doc = "      \"description\": \"The error name, if the execution failed\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"error_traceback\": {"]
    #[doc = "      \"description\": \"The error traceback, if the execution failed\","]
    #[doc = "      \"type\": \"array\","]
    #[doc = "      \"items\": {"]
    #[doc = "        \"type\": \"string\""]
    #[doc = "      }"]
    #[doc = "    },"]
    #[doc = "    \"execution_count\": {"]
    #[doc = "      \"description\": \"The kernel's execution counter\","]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    },"]
    #[doc = "    \"output\": {"]
    #[doc = "      \"description\": \"All output messages produced during execution, in order\","]
    #[doc = "      \"type\": \"array\","]
    #[doc = "      \"items\": {"]
    #[doc = "        \"$ref\": \"#/components/schemas/executeOutput\""]
    #[doc = "      }"]
    #[doc = "    },"]
    #[doc = "    \"status\": {"]
    #[doc = "      \"description\": \"Whether the execution succeeded or errored\","]
    #[doc = "      \"type\": \"string\","]
    #[doc = "      \"enum\": ["]
    #[doc = "        \"ok\","]
    #[doc = "        \"error\""]
    #[doc = "      ]"]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    pub struct ExecuteReply {
        #[doc = "The execution result as a MIME-keyed dictionary (from execute_result), if the execution produced a result"]
        #[serde(
            default,
            skip_serializing_if = ":: std :: collections :: HashMap::is_empty"
        )]
        pub data: ::std::collections::HashMap<::std::string::String, ::std::string::String>,
        #[doc = "The error message, if the execution failed"]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub error_message: ::std::option::Option<::std::string::String>,
        #[doc = "The error name, if the execution failed"]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub error_name: ::std::option::Option<::std::string::String>,
        #[doc = "The error traceback, if the execution failed"]
        #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
        pub error_traceback: ::std::vec::Vec<::std::string::String>,
        #[doc = "The kernel's execution counter"]
        pub execution_count: i64,
        #[doc = "All output messages produced during execution, in order"]
        pub output: ::std::vec::Vec<ExecuteOutput>,
        #[doc = "Whether the execution succeeded or errored"]
        pub status: ExecuteReplyStatus,
    }
    #[doc = "Whether the execution succeeded or errored"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"Whether the execution succeeded or errored\","]
    #[doc = "  \"type\": \"string\","]
    #[doc = "  \"enum\": ["]
    #[doc = "    \"ok\","]
    #[doc = "    \"error\""]
    #[doc = "  ]"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(
        :: serde :: Deserialize,
        :: serde :: Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum ExecuteReplyStatus {
        #[serde(rename = "ok")]
        Ok,
        #[serde(rename = "error")]
        Error,
    }
    impl ::std::fmt::Display for ExecuteReplyStatus {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Ok => f.write_str("ok"),
                Self::Error => f.write_str("error"),
            }
        }
    }
    impl ::std::str::FromStr for ExecuteReplyStatus {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "ok" => Ok(Self::Ok),
                "error" => Ok(Self::Error),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for ExecuteReplyStatus {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<&::std::string::String> for ExecuteReplyStatus {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for ExecuteReplyStatus {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    #[doc = "A request to execute code in a session"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"A request to execute code in a session\","]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"code\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"code\": {"]
    #[doc = "      \"description\": \"The code to execute\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"silent\": {"]
    #[doc = "      \"description\": \"If true, signals the kernel to execute quietly: no broadcast on iopub, no execute_result, and the execution_count is not incremented. Defaults to false.\","]
    #[doc = "      \"default\": false,"]
    #[doc = "      \"type\": \"boolean\""]
    #[doc = "    },"]
    #[doc = "    \"stop_on_error\": {"]
    #[doc = "      \"description\": \"If true (default), abort the execution queue on error. If false, queued execute requests will still be processed even if this one fails.\","]
    #[doc = "      \"default\": true,"]
    #[doc = "      \"type\": \"boolean\""]
    #[doc = "    },"]
    #[doc = "    \"store_history\": {"]
    #[doc = "      \"description\": \"If true (default), the code is stored in the kernel's history. Set to false for throwaway executions.\","]
    #[doc = "      \"default\": true,"]
    #[doc = "      \"type\": \"boolean\""]
    #[doc = "    },"]
    #[doc = "    \"timeout_seconds\": {"]
    #[doc = "      \"description\": \"Maximum number of seconds to wait for execution to complete. If not specified, the request will block indefinitely until execution finishes.\","]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    pub struct ExecuteRequest {
        #[doc = "The code to execute"]
        pub code: ::std::string::String,
        #[doc = "If true, signals the kernel to execute quietly: no broadcast on iopub, no execute_result, and the execution_count is not incremented. Defaults to false."]
        #[serde(default)]
        pub silent: bool,
        #[doc = "If true (default), abort the execution queue on error. If false, queued execute requests will still be processed even if this one fails."]
        #[serde(default = "defaults::default_bool::<true>")]
        pub stop_on_error: bool,
        #[doc = "If true (default), the code is stored in the kernel's history. Set to false for throwaway executions."]
        #[serde(default = "defaults::default_bool::<true>")]
        pub store_history: bool,
        #[doc = "Maximum number of seconds to wait for execution to complete. If not specified, the request will block indefinitely until execution finishes."]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub timeout_seconds: ::std::option::Option<i64>,
    }
    #[doc = "The execution queue for a session"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"The execution queue for a session\","]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"length\","]
    #[doc = "    \"pending\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"active\": {"]
    #[doc = "      \"description\": \"The execution request currently being evaluated, if any\","]
    #[doc = "      \"type\": \"object\""]
    #[doc = "    },"]
    #[doc = "    \"length\": {"]
    #[doc = "      \"description\": \"The number of items in the pending queue\","]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    },"]
    #[doc = "    \"pending\": {"]
    #[doc = "      \"description\": \"The queue of pending execution requests\","]
    #[doc = "      \"type\": \"array\","]
    #[doc = "      \"items\": {"]
    #[doc = "        \"type\": \"object\""]
    #[doc = "      }"]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    pub struct ExecutionQueue {
        #[doc = "The execution request currently being evaluated, if any"]
        #[serde(default, skip_serializing_if = "::serde_json::Map::is_empty")]
        pub active: ::serde_json::Map<::std::string::String, ::serde_json::Value>,
        #[doc = "The number of items in the pending queue"]
        pub length: i64,
        #[doc = "The queue of pending execution requests"]
        pub pending: ::std::vec::Vec<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    #[doc = "The mechansim for interrupting the session"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"The mechansim for interrupting the session\","]
    #[doc = "  \"type\": \"string\","]
    #[doc = "  \"enum\": ["]
    #[doc = "    \"signal\","]
    #[doc = "    \"message\""]
    #[doc = "  ]"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(
        :: serde :: Deserialize,
        :: serde :: Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum InterruptMode {
        #[serde(rename = "signal")]
        Signal,
        #[serde(rename = "message")]
        Message,
    }
    impl ::std::fmt::Display for InterruptMode {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Signal => f.write_str("signal"),
                Self::Message => f.write_str("message"),
            }
        }
    }
    impl ::std::str::FromStr for InterruptMode {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "signal" => Ok(Self::Signal),
                "message" => Ok(Self::Message),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for InterruptMode {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<&::std::string::String> for InterruptMode {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for InterruptMode {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    #[doc = "`NewSession`"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"argv\","]
    #[doc = "    \"continuation_prompt\","]
    #[doc = "    \"display_name\","]
    #[doc = "    \"env\","]
    #[doc = "    \"input_prompt\","]
    #[doc = "    \"interrupt_mode\","]
    #[doc = "    \"language\","]
    #[doc = "    \"session_id\","]
    #[doc = "    \"session_mode\","]
    #[doc = "    \"startup_environment\","]
    #[doc = "    \"username\","]
    #[doc = "    \"working_directory\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"argv\": {"]
    #[doc = "      \"description\": \"The program and command-line parameters for the session\","]
    #[doc = "      \"type\": \"array\","]
    #[doc = "      \"items\": {"]
    #[doc = "        \"type\": \"string\""]
    #[doc = "      }"]
    #[doc = "    },"]
    #[doc = "    \"connection_timeout\": {"]
    #[doc = "      \"description\": \"The number of seconds to wait for a connection to the session's ZeroMQ sockets before timing out\","]
    #[doc = "      \"default\": 30,"]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    },"]
    #[doc = "    \"continuation_prompt\": {"]
    #[doc = "      \"description\": \"The text to use to prompt for input continuations\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"display_name\": {"]
    #[doc = "      \"description\": \"A human-readable name for the session\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"env\": {"]
    #[doc = "      \"$ref\": \"#/components/schemas/envVarActions\""]
    #[doc = "    },"]
    #[doc = "    \"input_prompt\": {"]
    #[doc = "      \"description\": \"The text to use to prompt for input\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"interrupt_mode\": {"]
    #[doc = "      \"$ref\": \"#/components/schemas/interrupt_mode\""]
    #[doc = "    },"]
    #[doc = "    \"language\": {"]
    #[doc = "      \"description\": \"The interpreter language\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"notebook_uri\": {"]
    #[doc = "      \"description\": \"For notebook sessions, the URI of the notebook file\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"protocol_version\": {"]
    #[doc = "      \"description\": \"The Jupyter protocol version supported by the underlying kernel\","]
    #[doc = "      \"default\": \"5.3\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"session_id\": {"]
    #[doc = "      \"description\": \"A unique identifier for the session\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"session_mode\": {"]
    #[doc = "      \"$ref\": \"#/components/schemas/sessionMode\""]
    #[doc = "    },"]
    #[doc = "    \"startup_environment\": {"]
    #[doc = "      \"$ref\": \"#/components/schemas/startupEnvironment\""]
    #[doc = "    },"]
    #[doc = "    \"startup_environment_arg\": {"]
    #[doc = "      \"description\": \"The command or script to run before starting the session\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"username\": {"]
    #[doc = "      \"description\": \"The username of the user who owns the session\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"working_directory\": {"]
    #[doc = "      \"description\": \"The working directory in which to start the session.\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    pub struct NewSession {
        #[doc = "The program and command-line parameters for the session"]
        pub argv: ::std::vec::Vec<::std::string::String>,
        #[doc = "The number of seconds to wait for a connection to the session's ZeroMQ sockets before timing out"]
        #[serde(default = "defaults::default_u64::<i64, 30>")]
        pub connection_timeout: i64,
        #[doc = "The text to use to prompt for input continuations"]
        pub continuation_prompt: ::std::string::String,
        #[doc = "A human-readable name for the session"]
        pub display_name: ::std::string::String,
        pub env: EnvVarActions,
        #[doc = "The text to use to prompt for input"]
        pub input_prompt: ::std::string::String,
        pub interrupt_mode: InterruptMode,
        #[doc = "The interpreter language"]
        pub language: ::std::string::String,
        #[doc = "For notebook sessions, the URI of the notebook file"]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub notebook_uri: ::std::option::Option<::std::string::String>,
        #[doc = "The Jupyter protocol version supported by the underlying kernel"]
        #[serde(default = "defaults::new_session_protocol_version")]
        pub protocol_version: ::std::string::String,
        #[doc = "A unique identifier for the session"]
        pub session_id: ::std::string::String,
        pub session_mode: SessionMode,
        pub startup_environment: StartupEnvironment,
        #[doc = "The command or script to run before starting the session"]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub startup_environment_arg: ::std::option::Option<::std::string::String>,
        #[doc = "The username of the user who owns the session"]
        pub username: ::std::string::String,
        #[doc = "The working directory in which to start the session."]
        pub working_directory: ::std::string::String,
    }
    #[doc = "`NewSessionResponse`"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"session_id\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"session_id\": {"]
    #[doc = "      \"description\": \"A unique identifier for the session\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    pub struct NewSessionResponse {
        #[doc = "A unique identifier for the session"]
        pub session_id: ::std::string::String,
    }
    #[doc = "`ResourceUsage`"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"cpu_percent\","]
    #[doc = "    \"memory_bytes\","]
    #[doc = "    \"sampling_period_ms\","]
    #[doc = "    \"thread_count\","]
    #[doc = "    \"timestamp\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"cpu_percent\": {"]
    #[doc = "      \"description\": \"The percentage of CPU used by the kernel process and its child processes\","]
    #[doc = "      \"type\": \"integer\","]
    #[doc = "      \"format\": \"int64\""]
    #[doc = "    },"]
    #[doc = "    \"memory_bytes\": {"]
    #[doc = "      \"description\": \"The amount of memory used by the kernel process and all of its child processes in bytes\","]
    #[doc = "      \"type\": \"integer\","]
    #[doc = "      \"format\": \"int64\""]
    #[doc = "    },"]
    #[doc = "    \"sampling_period_ms\": {"]
    #[doc = "      \"description\": \"The sampling period in milliseconds over which the resource usage was measured\","]
    #[doc = "      \"type\": \"integer\","]
    #[doc = "      \"format\": \"int64\""]
    #[doc = "    },"]
    #[doc = "    \"thread_count\": {"]
    #[doc = "      \"description\": \"The total number of threads used by the kernel process and its child processes (Linux only)\","]
    #[doc = "      \"type\": \"integer\","]
    #[doc = "      \"format\": \"int64\""]
    #[doc = "    },"]
    #[doc = "    \"timestamp\": {"]
    #[doc = "      \"description\": \"A Unix timestamp in milliseconds indicating when the resource usage was sampled\","]
    #[doc = "      \"type\": \"integer\","]
    #[doc = "      \"format\": \"int64\""]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    pub struct ResourceUsage {
        #[doc = "The percentage of CPU used by the kernel process and its child processes"]
        pub cpu_percent: i64,
        #[doc = "The amount of memory used by the kernel process and all of its child processes in bytes"]
        pub memory_bytes: i64,
        #[doc = "The sampling period in milliseconds over which the resource usage was measured"]
        pub sampling_period_ms: i64,
        #[doc = "The total number of threads used by the kernel process and its child processes (Linux only)"]
        pub thread_count: i64,
        #[doc = "A Unix timestamp in milliseconds indicating when the resource usage was sampled"]
        pub timestamp: i64,
    }
    #[doc = "`RestartSession`"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"env\": {"]
    #[doc = "      \"$ref\": \"#/components/schemas/envVarActions\""]
    #[doc = "    },"]
    #[doc = "    \"working_directory\": {"]
    #[doc = "      \"description\": \"The desired working directory for the session after restart, if different from the session's working directory at startup\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    pub struct RestartSession {
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub env: ::std::option::Option<EnvVarActions>,
        #[doc = "The desired working directory for the session after restart, if different from the session's working directory at startup"]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub working_directory: ::std::option::Option<::std::string::String>,
    }
    impl ::std::default::Default for RestartSession {
        fn default() -> Self {
            Self {
                env: Default::default(),
                working_directory: Default::default(),
            }
        }
    }
    #[doc = "`ServerConfiguration`"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"idle_shutdown_hours\": {"]
    #[doc = "      \"description\": \"The number of hours the server will wait before shutting down idle sessions (-1 if idle shutdown is disabled)\","]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    },"]
    #[doc = "    \"log_level\": {"]
    #[doc = "      \"description\": \"The current log level\","]
    #[doc = "      \"type\": \"string\","]
    #[doc = "      \"enum\": ["]
    #[doc = "        \"trace\","]
    #[doc = "        \"debug\","]
    #[doc = "        \"info\","]
    #[doc = "        \"warn\","]
    #[doc = "        \"error\""]
    #[doc = "      ]"]
    #[doc = "    },"]
    #[doc = "    \"resource_sample_interval_ms\": {"]
    #[doc = "      \"description\": \"The interval in milliseconds at which resource usage is sampled. A value of 0 disables resource usage sampling.\","]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    pub struct ServerConfiguration {
        #[doc = "The number of hours the server will wait before shutting down idle sessions (-1 if idle shutdown is disabled)"]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub idle_shutdown_hours: ::std::option::Option<i64>,
        #[doc = "The current log level"]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub log_level: ::std::option::Option<ServerConfigurationLogLevel>,
        #[doc = "The interval in milliseconds at which resource usage is sampled. A value of 0 disables resource usage sampling."]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub resource_sample_interval_ms: ::std::option::Option<i64>,
    }
    impl ::std::default::Default for ServerConfiguration {
        fn default() -> Self {
            Self {
                idle_shutdown_hours: Default::default(),
                log_level: Default::default(),
                resource_sample_interval_ms: Default::default(),
            }
        }
    }
    #[doc = "The current log level"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"The current log level\","]
    #[doc = "  \"type\": \"string\","]
    #[doc = "  \"enum\": ["]
    #[doc = "    \"trace\","]
    #[doc = "    \"debug\","]
    #[doc = "    \"info\","]
    #[doc = "    \"warn\","]
    #[doc = "    \"error\""]
    #[doc = "  ]"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(
        :: serde :: Deserialize,
        :: serde :: Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum ServerConfigurationLogLevel {
        #[serde(rename = "trace")]
        Trace,
        #[serde(rename = "debug")]
        Debug,
        #[serde(rename = "info")]
        Info,
        #[serde(rename = "warn")]
        Warn,
        #[serde(rename = "error")]
        Error,
    }
    impl ::std::fmt::Display for ServerConfigurationLogLevel {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Trace => f.write_str("trace"),
                Self::Debug => f.write_str("debug"),
                Self::Info => f.write_str("info"),
                Self::Warn => f.write_str("warn"),
                Self::Error => f.write_str("error"),
            }
        }
    }
    impl ::std::str::FromStr for ServerConfigurationLogLevel {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "trace" => Ok(Self::Trace),
                "debug" => Ok(Self::Debug),
                "info" => Ok(Self::Info),
                "warn" => Ok(Self::Warn),
                "error" => Ok(Self::Error),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for ServerConfigurationLogLevel {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<&::std::string::String> for ServerConfigurationLogLevel {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for ServerConfigurationLogLevel {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    #[doc = "`ServerStatus`"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"active\","]
    #[doc = "    \"busy\","]
    #[doc = "    \"busy_seconds\","]
    #[doc = "    \"idle_seconds\","]
    #[doc = "    \"process_id\","]
    #[doc = "    \"sessions\","]
    #[doc = "    \"started\","]
    #[doc = "    \"uptime_seconds\","]
    #[doc = "    \"version\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"active\": {"]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    },"]
    #[doc = "    \"busy\": {"]
    #[doc = "      \"type\": \"boolean\""]
    #[doc = "    },"]
    #[doc = "    \"busy_seconds\": {"]
    #[doc = "      \"description\": \"The number of seconds any session has been busy, or 0 if all sessions are idle\","]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    },"]
    #[doc = "    \"idle_seconds\": {"]
    #[doc = "      \"description\": \"The number of seconds all sessions have been idle, or 0 if any session is busy\","]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    },"]
    #[doc = "    \"process_id\": {"]
    #[doc = "      \"description\": \"The server's operating system process identifier\","]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    },"]
    #[doc = "    \"sessions\": {"]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    },"]
    #[doc = "    \"started\": {"]
    #[doc = "      \"description\": \"An ISO 8601 timestamp of when the server was started\","]
    #[doc = "      \"type\": \"string\","]
    #[doc = "      \"format\": \"date-time\""]
    #[doc = "    },"]
    #[doc = "    \"uptime_seconds\": {"]
    #[doc = "      \"description\": \"The number of seconds the server has been running\","]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    },"]
    #[doc = "    \"version\": {"]
    #[doc = "      \"description\": \"The version of the server\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    pub struct ServerStatus {
        pub active: i64,
        pub busy: bool,
        #[doc = "The number of seconds any session has been busy, or 0 if all sessions are idle"]
        pub busy_seconds: i64,
        #[doc = "The number of seconds all sessions have been idle, or 0 if any session is busy"]
        pub idle_seconds: i64,
        #[doc = "The server's operating system process identifier"]
        pub process_id: i64,
        pub sessions: i64,
        #[doc = "An ISO 8601 timestamp of when the server was started"]
        pub started: ::chrono::DateTime<::chrono::offset::Utc>,
        #[doc = "The number of seconds the server has been running"]
        pub uptime_seconds: i64,
        #[doc = "The version of the server"]
        pub version: ::std::string::String,
    }
    #[doc = "`SessionList`"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"sessions\","]
    #[doc = "    \"total\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"sessions\": {"]
    #[doc = "      \"type\": \"array\","]
    #[doc = "      \"items\": {"]
    #[doc = "        \"$ref\": \"#/components/schemas/activeSession\""]
    #[doc = "      }"]
    #[doc = "    },"]
    #[doc = "    \"total\": {"]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    pub struct SessionList {
        pub sessions: ::std::vec::Vec<ActiveSession>,
        pub total: i64,
    }
    #[doc = "The mode in which the session is running"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"The mode in which the session is running\","]
    #[doc = "  \"type\": \"string\","]
    #[doc = "  \"enum\": ["]
    #[doc = "    \"console\","]
    #[doc = "    \"notebook\","]
    #[doc = "    \"background\""]
    #[doc = "  ]"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(
        :: serde :: Deserialize,
        :: serde :: Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum SessionMode {
        #[serde(rename = "console")]
        Console,
        #[serde(rename = "notebook")]
        Notebook,
        #[serde(rename = "background")]
        Background,
    }
    impl ::std::fmt::Display for SessionMode {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Console => f.write_str("console"),
                Self::Notebook => f.write_str("notebook"),
                Self::Background => f.write_str("background"),
            }
        }
    }
    impl ::std::str::FromStr for SessionMode {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "console" => Ok(Self::Console),
                "notebook" => Ok(Self::Notebook),
                "background" => Ok(Self::Background),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for SessionMode {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<&::std::string::String> for SessionMode {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for SessionMode {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    #[doc = "The kernel's startup environment: 'none' for normal startup, 'shell' for a login shell, 'command' for a preflight command, 'script' to run a script. Only relevant on POSIX-like systems."]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"The kernel's startup environment: 'none' for normal startup, 'shell' for a login shell, 'command' for a preflight command, 'script' to run a script. Only relevant on POSIX-like systems.\","]
    #[doc = "  \"type\": \"string\","]
    #[doc = "  \"enum\": ["]
    #[doc = "    \"none\","]
    #[doc = "    \"shell\","]
    #[doc = "    \"command\","]
    #[doc = "    \"script\""]
    #[doc = "  ]"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(
        :: serde :: Deserialize,
        :: serde :: Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum StartupEnvironment {
        #[serde(rename = "none")]
        None,
        #[serde(rename = "shell")]
        Shell,
        #[serde(rename = "command")]
        Command,
        #[serde(rename = "script")]
        Script,
    }
    impl ::std::fmt::Display for StartupEnvironment {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::None => f.write_str("none"),
                Self::Shell => f.write_str("shell"),
                Self::Command => f.write_str("command"),
                Self::Script => f.write_str("script"),
            }
        }
    }
    impl ::std::str::FromStr for StartupEnvironment {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "none" => Ok(Self::None),
                "shell" => Ok(Self::Shell),
                "command" => Ok(Self::Command),
                "script" => Ok(Self::Script),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for StartupEnvironment {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<&::std::string::String> for StartupEnvironment {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for StartupEnvironment {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    #[doc = "`StartupError`"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"error\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"error\": {"]
    #[doc = "      \"$ref\": \"#/components/schemas/error\""]
    #[doc = "    },"]
    #[doc = "    \"exit_code\": {"]
    #[doc = "      \"description\": \"The exit code of the process, if it exited\","]
    #[doc = "      \"type\": \"integer\""]
    #[doc = "    },"]
    #[doc = "    \"output\": {"]
    #[doc = "      \"description\": \"The output of the process (combined stdout and stderr) emitted during startup, if any\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    pub struct StartupError {
        pub error: Error,
        #[doc = "The exit code of the process, if it exited"]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub exit_code: ::std::option::Option<i64>,
        #[doc = "The output of the process (combined stdout and stderr) emitted during startup, if any"]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub output: ::std::option::Option<::std::string::String>,
    }
    #[doc = "The status of the session"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"The status of the session\","]
    #[doc = "  \"type\": \"string\","]
    #[doc = "  \"enum\": ["]
    #[doc = "    \"uninitialized\","]
    #[doc = "    \"starting\","]
    #[doc = "    \"ready\","]
    #[doc = "    \"idle\","]
    #[doc = "    \"busy\","]
    #[doc = "    \"offline\","]
    #[doc = "    \"exited\""]
    #[doc = "  ]"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(
        :: serde :: Deserialize,
        :: serde :: Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum Status {
        #[serde(rename = "uninitialized")]
        Uninitialized,
        #[serde(rename = "starting")]
        Starting,
        #[serde(rename = "ready")]
        Ready,
        #[serde(rename = "idle")]
        Idle,
        #[serde(rename = "busy")]
        Busy,
        #[serde(rename = "offline")]
        Offline,
        #[serde(rename = "exited")]
        Exited,
    }
    impl ::std::fmt::Display for Status {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Uninitialized => f.write_str("uninitialized"),
                Self::Starting => f.write_str("starting"),
                Self::Ready => f.write_str("ready"),
                Self::Idle => f.write_str("idle"),
                Self::Busy => f.write_str("busy"),
                Self::Offline => f.write_str("offline"),
                Self::Exited => f.write_str("exited"),
            }
        }
    }
    impl ::std::str::FromStr for Status {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "uninitialized" => Ok(Self::Uninitialized),
                "starting" => Ok(Self::Starting),
                "ready" => Ok(Self::Ready),
                "idle" => Ok(Self::Idle),
                "busy" => Ok(Self::Busy),
                "offline" => Ok(Self::Offline),
                "exited" => Ok(Self::Exited),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for Status {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<&::std::string::String> for Status {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for Status {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    #[doc = "`VarAction`"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"action\","]
    #[doc = "    \"name\","]
    #[doc = "    \"value\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"action\": {"]
    #[doc = "      \"$ref\": \"#/components/schemas/varActionType\""]
    #[doc = "    },"]
    #[doc = "    \"name\": {"]
    #[doc = "      \"description\": \"The name of the variable to act on\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"value\": {"]
    #[doc = "      \"description\": \"The value to replace, append, or prepend\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    pub struct VarAction {
        pub action: VarActionType,
        #[doc = "The name of the variable to act on"]
        pub name: ::std::string::String,
        #[doc = "The value to replace, append, or prepend"]
        pub value: ::std::string::String,
    }
    #[doc = "The type of action to perform on the environment variable"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"The type of action to perform on the environment variable\","]
    #[doc = "  \"type\": \"string\","]
    #[doc = "  \"enum\": ["]
    #[doc = "    \"replace\","]
    #[doc = "    \"append\","]
    #[doc = "    \"prepend\""]
    #[doc = "  ]"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(
        :: serde :: Deserialize,
        :: serde :: Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum VarActionType {
        #[serde(rename = "replace")]
        Replace,
        #[serde(rename = "append")]
        Append,
        #[serde(rename = "prepend")]
        Prepend,
    }
    impl ::std::fmt::Display for VarActionType {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Replace => f.write_str("replace"),
                Self::Append => f.write_str("append"),
                Self::Prepend => f.write_str("prepend"),
            }
        }
    }
    impl ::std::str::FromStr for VarActionType {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "replace" => Ok(Self::Replace),
                "append" => Ok(Self::Append),
                "prepend" => Ok(Self::Prepend),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for VarActionType {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<&::std::string::String> for VarActionType {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for VarActionType {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    #[doc = r" Generation of default values for serde."]
    pub mod defaults {
        pub(super) fn default_bool<const V: bool>() -> bool {
            V
        }
        pub(super) fn default_u64<T, const V: u64>() -> T
        where
            T: ::std::convert::TryFrom<u64>,
            <T as ::std::convert::TryFrom<u64>>::Error: ::std::fmt::Debug,
        {
            T::try_from(V).unwrap()
        }
        pub(super) fn new_session_protocol_version() -> ::std::string::String {
            "5.3".to_string()
        }
    }
}
#[derive(Clone, Debug)]
#[doc = "Client for Kallichore API\n\nKallichore is a Jupyter kernel gateway and supervisor\n\nVersion: 1.0.0"]
pub struct Client {
    pub(crate) baseurl: String,
    pub(crate) client: reqwest::Client,
}
impl Client {
    #[doc = r" Create a new client."]
    #[doc = r""]
    #[doc = r" `baseurl` is the base URL provided to the internal"]
    #[doc = r" `reqwest::Client`, and should include a scheme and hostname,"]
    #[doc = r" as well as port and a path stem if applicable."]
    pub fn new(baseurl: &str) -> Self {
        #[cfg(not(target_arch = "wasm32"))]
        let client = {
            let dur = ::std::time::Duration::from_secs(15u64);
            reqwest::ClientBuilder::new()
                .connect_timeout(dur)
                .timeout(dur)
        };
        #[cfg(target_arch = "wasm32")]
        let client = reqwest::ClientBuilder::new();
        Self::new_with_client(baseurl, client.build().unwrap())
    }
    #[doc = r" Construct a new client with an existing `reqwest::Client`,"]
    #[doc = r" allowing more control over its configuration."]
    #[doc = r""]
    #[doc = r" `baseurl` is the base URL provided to the internal"]
    #[doc = r" `reqwest::Client`, and should include a scheme and hostname,"]
    #[doc = r" as well as port and a path stem if applicable."]
    pub fn new_with_client(baseurl: &str, client: reqwest::Client) -> Self {
        Self {
            baseurl: baseurl.to_string(),
            client,
        }
    }
}
impl ClientInfo<()> for Client {
    fn api_version() -> &'static str {
        "1.0.0"
    }
    fn baseurl(&self) -> &str {
        self.baseurl.as_str()
    }
    fn client(&self) -> &reqwest::Client {
        &self.client
    }
    fn inner(&self) -> &() {
        &()
    }
}
impl ClientHooks<()> for &Client {}
#[allow(clippy::all)]
impl Client {
    #[doc = "Notify the server that a client is connected\n\nSends a `POST` request to `/client_heartbeat`\n\n"]
    pub async fn client_heartbeat<'a>(
        &'a self,
        body: &'a types::ClientHeartbeat,
    ) -> Result<ResponseValue<::serde_json::Value>, Error<()>> {
        let url = format!("{}/client_heartbeat", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "client_heartbeat",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    #[doc = "Get the server configuration\n\nSends a `GET` request to `/server_configuration`\n\n"]
    pub async fn get_server_configuration<'a>(
        &'a self,
    ) -> Result<ResponseValue<types::ServerConfiguration>, Error<()>> {
        let url = format!("{}/server_configuration", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "get_server_configuration",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    #[doc = "Change the server configuration\n\nSends a `POST` request to `/server_configuration`\n\n"]
    pub async fn set_server_configuration<'a>(
        &'a self,
        body: &'a types::ServerConfiguration,
    ) -> Result<ResponseValue<::serde_json::Value>, Error<()>> {
        let url = format!("{}/server_configuration", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "set_server_configuration",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    #[doc = "List active sessions\n\nSends a `GET` request to `/sessions`\n\n"]
    pub async fn list_sessions<'a>(
        &'a self,
    ) -> Result<ResponseValue<types::SessionList>, Error<()>> {
        let url = format!("{}/sessions", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "list_sessions",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    #[doc = "Create a new session\n\nSends a `PUT` request to `/sessions`\n\n"]
    pub async fn new_session<'a>(
        &'a self,
        body: &'a types::NewSession,
    ) -> Result<ResponseValue<types::NewSessionResponse>, Error<()>> {
        let url = format!("{}/sessions", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .put(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "new_session",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    #[doc = "Get session details\n\nSends a `GET` request to `/sessions/{session_id}`\n\n"]
    pub async fn get_session<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Result<ResponseValue<types::ActiveSession>, Error<()>> {
        let url = format!(
            "{}/sessions/{}",
            self.baseurl,
            encode_path(&session_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "get_session",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    #[doc = "Delete session\n\nSends a `DELETE` request to `/sessions/{session_id}`\n\n"]
    pub async fn delete_session<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Result<ResponseValue<::serde_json::Value>, Error<()>> {
        let url = format!(
            "{}/sessions/{}",
            self.baseurl,
            encode_path(&session_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .delete(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "delete_session",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    #[doc = "Adopt an existing session\n\nSends a `PUT` request to `/sessions/{session_id}/adopt`\n\n"]
    pub async fn adopt_session<'a>(
        &'a self,
        session_id: &'a str,
        body: &'a types::ConnectionInfo,
    ) -> Result<ResponseValue<::serde_json::Value>, Error<()>> {
        let url = format!(
            "{}/sessions/{}/adopt",
            self.baseurl,
            encode_path(&session_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .put(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "adopt_session",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    #[doc = "Upgrade to a WebSocket or domain socket for channel communication\n\nSends a `GET` request to `/sessions/{session_id}/channels`\n\n"]
    pub async fn channels_upgrade<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Result<ResponseValue<::std::string::String>, Error<()>> {
        let url = format!(
            "{}/sessions/{}/channels",
            self.baseurl,
            encode_path(&session_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "channels_upgrade",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    #[doc = "Get Jupyter connection information for the session\n\nSends a `GET` request to `/sessions/{session_id}/connection_info`\n\n"]
    pub async fn connection_info<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Result<ResponseValue<types::ConnectionInfo>, Error<()>> {
        let url = format!(
            "{}/sessions/{}/connection_info",
            self.baseurl,
            encode_path(&session_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "connection_info",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    #[doc = "Execute code and return results\n\nSends a `POST` request to `/sessions/{session_id}/execute`\n\n"]
    pub async fn execute_code<'a>(
        &'a self,
        session_id: &'a str,
        body: &'a types::ExecuteRequest,
    ) -> Result<ResponseValue<types::ExecuteReply>, Error<()>> {
        let url = format!(
            "{}/sessions/{}/execute",
            self.baseurl,
            encode_path(&session_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "execute_code",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    #[doc = "Interrupt session\n\nSends a `POST` request to `/sessions/{session_id}/interrupt`\n\n"]
    pub async fn interrupt_session<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Result<ResponseValue<::serde_json::Value>, Error<()>> {
        let url = format!(
            "{}/sessions/{}/interrupt",
            self.baseurl,
            encode_path(&session_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "interrupt_session",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    #[doc = "Force quit session\n\nSends a `POST` request to `/sessions/{session_id}/kill`\n\n"]
    pub async fn kill_session<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Result<ResponseValue<::serde_json::Value>, Error<()>> {
        let url = format!(
            "{}/sessions/{}/kill",
            self.baseurl,
            encode_path(&session_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "kill_session",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    #[doc = "Restart a session\n\nSends a `POST` request to `/sessions/{session_id}/restart`\n\n"]
    pub async fn restart_session<'a>(
        &'a self,
        session_id: &'a str,
        body: &'a types::RestartSession,
    ) -> Result<ResponseValue<::serde_json::Value>, Error<()>> {
        let url = format!(
            "{}/sessions/{}/restart",
            self.baseurl,
            encode_path(&session_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "restart_session",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    #[doc = "Start a session\n\nSends a `POST` request to `/sessions/{session_id}/start`\n\n"]
    pub async fn start_session<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Result<ResponseValue<::serde_json::Value>, Error<()>> {
        let url = format!(
            "{}/sessions/{}/start",
            self.baseurl,
            encode_path(&session_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "start_session",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    #[doc = "Shut down all sessions and the server itself\n\nSends a `POST` request to `/shutdown`\n\n"]
    pub async fn shutdown_server<'a>(
        &'a self,
    ) -> Result<ResponseValue<::serde_json::Value>, Error<()>> {
        let url = format!("{}/shutdown", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "shutdown_server",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    #[doc = "Get server status and information\n\nSends a `GET` request to `/status`\n\n"]
    pub async fn server_status<'a>(
        &'a self,
    ) -> Result<ResponseValue<types::ServerStatus>, Error<()>> {
        let url = format!("{}/status", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "server_status",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
}
#[doc = r" Items consumers will typically use such as the Client."]
pub mod prelude {
    #[allow(unused_imports)]
    pub use super::Client;
}
