// @generated — regenerated by build.rs from vendor/kallichore.json.
// To refresh: edit vendor/kallichore.json (or re-run `cargo build`).
// Do not edit by hand; changes will be overwritten on the next build.
#[allow(unused_imports)]
use progenitor_client::{encode_path, ClientHooks, OperationInfo, RequestBuilderExt};
#[allow(unused_imports)]
pub use progenitor_client::{ByteStream, ClientInfo, Error, ResponseValue};
/// Types used as operation parameters and responses.
#[allow(clippy::all)]
pub mod types {
    /// Error types.
    pub mod error {
        /// Error from a `TryFrom` or `FromStr` implementation.
        pub struct ConversionError(::std::borrow::Cow<'static, str>);
        impl ::std::error::Error for ConversionError {}
        impl ::std::fmt::Display for ConversionError {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
                ::std::fmt::Display::fmt(&self.0, f)
            }
        }
        impl ::std::fmt::Debug for ConversionError {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
                ::std::fmt::Debug::fmt(&self.0, f)
            }
        }
        impl From<&'static str> for ConversionError {
            fn from(value: &'static str) -> Self {
                Self(value.into())
            }
        }
        impl From<String> for ConversionError {
            fn from(value: String) -> Self {
                Self(value.into())
            }
        }
    }
    ///`ActiveSession`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "object",
    ///  "required": [
    ///    "argv",
    ///    "busy_seconds",
    ///    "connected",
    ///    "continuation_prompt",
    ///    "display_name",
    ///    "execution_queue",
    ///    "idle_seconds",
    ///    "input_prompt",
    ///    "interrupt_mode",
    ///    "kernel_info",
    ///    "language",
    ///    "session_id",
    ///    "session_mode",
    ///    "started",
    ///    "status",
    ///    "username",
    ///    "working_directory"
    ///  ],
    ///  "properties": {
    ///    "argv": {
    ///      "description": "The program and command-line parameters for the session",
    ///      "type": "array",
    ///      "items": {
    ///        "type": "string"
    ///      }
    ///    },
    ///    "busy_seconds": {
    ///      "description": "The number of seconds the session has been busy, or 0 if the session is idle",
    ///      "type": "integer"
    ///    },
    ///    "connected": {
    ///      "description": "Whether the session is connected to a client",
    ///      "type": "boolean"
    ///    },
    ///    "continuation_prompt": {
    ///      "description": "The text to use to prompt for input continuations",
    ///      "type": "string"
    ///    },
    ///    "display_name": {
    ///      "description": "A human-readable name for the session",
    ///      "type": "string"
    ///    },
    ///    "execution_queue": {
    ///      "$ref": "#/components/schemas/execution_queue"
    ///    },
    ///    "idle_seconds": {
    ///      "description": "The number of seconds the session has been idle, or 0 if the session is busy",
    ///      "type": "integer"
    ///    },
    ///    "initial_env": {
    ///      "description": "The environment variables set when the session was started",
    ///      "type": "object",
    ///      "additionalProperties": {
    ///        "type": "string"
    ///      }
    ///    },
    ///    "input_prompt": {
    ///      "description": "The text to use to prompt for input",
    ///      "type": "string"
    ///    },
    ///    "interrupt_mode": {
    ///      "$ref": "#/components/schemas/interrupt_mode"
    ///    },
    ///    "kernel_info": {
    ///      "description": "The kernel information, as returned by the kernel_info_request message",
    ///      "type": "object"
    ///    },
    ///    "language": {
    ///      "description": "The interpreter language",
    ///      "type": "string"
    ///    },
    ///    "notebook_uri": {
    ///      "description": "For notebook sessions, the URI of the notebook file",
    ///      "type": "string"
    ///    },
    ///    "process_id": {
    ///      "description": "The underlying process ID of the session, if the session is running.",
    ///      "type": "integer"
    ///    },
    ///    "resource_usage": {
    ///      "$ref": "#/components/schemas/resourceUsage"
    ///    },
    ///    "session_id": {
    ///      "description": "A unique identifier for the session",
    ///      "type": "string"
    ///    },
    ///    "session_mode": {
    ///      "$ref": "#/components/schemas/sessionMode"
    ///    },
    ///    "socket_path": {
    ///      "description": "The path to the Unix domain socket used to send/receive data from the session, if applicable",
    ///      "type": "string"
    ///    },
    ///    "started": {
    ///      "description": "An ISO 8601 timestamp of when the session was started",
    ///      "type": "string",
    ///      "format": "date-time"
    ///    },
    ///    "status": {
    ///      "$ref": "#/components/schemas/status"
    ///    },
    ///    "username": {
    ///      "description": "The username of the user who owns the session",
    ///      "type": "string"
    ///    },
    ///    "working_directory": {
    ///      "description": "The session's current working directory",
    ///      "type": "string"
    ///    }
    ///  }
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ActiveSession {
        ///The program and command-line parameters for the session
        pub argv: ::std::vec::Vec<::std::string::String>,
        ///The number of seconds the session has been busy, or 0 if the session is idle
        pub busy_seconds: i64,
        ///Whether the session is connected to a client
        pub connected: bool,
        ///The text to use to prompt for input continuations
        pub continuation_prompt: ::std::string::String,
        ///A human-readable name for the session
        pub display_name: ::std::string::String,
        pub execution_queue: ExecutionQueue,
        ///The number of seconds the session has been idle, or 0 if the session is busy
        pub idle_seconds: i64,
        ///The environment variables set when the session was started
        #[serde(
            default,
            skip_serializing_if = ":: std :: collections :: HashMap::is_empty"
        )]
        pub initial_env: ::std::collections::HashMap<::std::string::String, ::std::string::String>,
        ///The text to use to prompt for input
        pub input_prompt: ::std::string::String,
        pub interrupt_mode: InterruptMode,
        ///The kernel information, as returned by the kernel_info_request message
        pub kernel_info: ::serde_json::Map<::std::string::String, ::serde_json::Value>,
        ///The interpreter language
        pub language: ::std::string::String,
        ///For notebook sessions, the URI of the notebook file
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub notebook_uri: ::std::option::Option<::std::string::String>,
        ///The underlying process ID of the session, if the session is running.
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub process_id: ::std::option::Option<i64>,
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub resource_usage: ::std::option::Option<ResourceUsage>,
        ///A unique identifier for the session
        pub session_id: ::std::string::String,
        pub session_mode: SessionMode,
        ///The path to the Unix domain socket used to send/receive data from the session, if applicable
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub socket_path: ::std::option::Option<::std::string::String>,
        ///An ISO 8601 timestamp of when the session was started
        pub started: ::chrono::DateTime<::chrono::offset::Utc>,
        pub status: Status,
        ///The username of the user who owns the session
        pub username: ::std::string::String,
        ///The session's current working directory
        pub working_directory: ::std::string::String,
    }
    ///`ClientHeartbeat`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "object",
    ///  "properties": {
    ///    "process_id": {
    ///      "description": "The process ID of the client sending the heartbeat",
    ///      "type": "integer"
    ///    }
    ///  }
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ClientHeartbeat {
        ///The process ID of the client sending the heartbeat
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub process_id: ::std::option::Option<i64>,
    }
    impl ::std::default::Default for ClientHeartbeat {
        fn default() -> Self {
            Self {
                process_id: Default::default(),
            }
        }
    }
    ///Connection information for an existing session
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "description": "Connection information for an existing session",
    ///  "type": "object",
    ///  "required": [
    ///    "control_port",
    ///    "hb_port",
    ///    "iopub_port",
    ///    "ip",
    ///    "key",
    ///    "shell_port",
    ///    "signature_scheme",
    ///    "stdin_port",
    ///    "transport"
    ///  ],
    ///  "properties": {
    ///    "control_port": {
    ///      "description": "The port for control messages",
    ///      "type": "integer"
    ///    },
    ///    "hb_port": {
    ///      "description": "The port for heartbeat messages",
    ///      "type": "integer"
    ///    },
    ///    "iopub_port": {
    ///      "description": "The port for IOPub messages",
    ///      "type": "integer"
    ///    },
    ///    "ip": {
    ///      "description": "The IP address for the connection",
    ///      "type": "string"
    ///    },
    ///    "key": {
    ///      "description": "The key for messages",
    ///      "type": "string"
    ///    },
    ///    "shell_port": {
    ///      "description": "The port for shell messages",
    ///      "type": "integer"
    ///    },
    ///    "signature_scheme": {
    ///      "description": "The signature scheme for messages",
    ///      "type": "string"
    ///    },
    ///    "stdin_port": {
    ///      "description": "The port for stdin messages",
    ///      "type": "integer"
    ///    },
    ///    "transport": {
    ///      "description": "The transport protocol",
    ///      "type": "string"
    ///    }
    ///  }
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ConnectionInfo {
        ///The port for control messages
        pub control_port: i64,
        ///The port for heartbeat messages
        pub hb_port: i64,
        ///The port for IOPub messages
        pub iopub_port: i64,
        ///The IP address for the connection
        pub ip: ::std::string::String,
        ///The key for messages
        pub key: ::std::string::String,
        ///The port for shell messages
        pub shell_port: i64,
        ///The signature scheme for messages
        pub signature_scheme: ::std::string::String,
        ///The port for stdin messages
        pub stdin_port: i64,
        ///The transport protocol
        pub transport: ::std::string::String,
    }
    ///A list of environment variable actions to perform
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "description": "A list of environment variable actions to perform",
    ///  "type": "array",
    ///  "items": {
    ///    "$ref": "#/components/schemas/varAction"
    ///  }
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    #[serde(transparent)]
    pub struct EnvVarActions(pub ::std::vec::Vec<VarAction>);
    impl ::std::ops::Deref for EnvVarActions {
        type Target = ::std::vec::Vec<VarAction>;
        fn deref(&self) -> &::std::vec::Vec<VarAction> {
            &self.0
        }
    }
    impl ::std::convert::From<EnvVarActions> for ::std::vec::Vec<VarAction> {
        fn from(value: EnvVarActions) -> Self {
            value.0
        }
    }
    impl ::std::convert::From<::std::vec::Vec<VarAction>> for EnvVarActions {
        fn from(value: ::std::vec::Vec<VarAction>) -> Self {
            Self(value)
        }
    }
    ///`Error`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "object",
    ///  "required": [
    ///    "code",
    ///    "message"
    ///  ],
    ///  "properties": {
    ///    "code": {
    ///      "type": "string"
    ///    },
    ///    "details": {
    ///      "type": "string"
    ///    },
    ///    "message": {
    ///      "type": "string"
    ///    }
    ///  }
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct Error {
        pub code: ::std::string::String,
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub details: ::std::option::Option<::std::string::String>,
        pub message: ::std::string::String,
    }
    ///A single output message produced during code execution
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "description": "A single output message produced during code execution",
    ///  "type": "object",
    ///  "required": [
    ///    "type"
    ///  ],
    ///  "properties": {
    ///    "data": {
    ///      "description": "MIME-keyed data, for display_data output",
    ///      "type": "object",
    ///      "additionalProperties": {
    ///        "type": "string"
    ///      }
    ///    },
    ///    "error_message": {
    ///      "description": "The error message, for error output",
    ///      "type": "string"
    ///    },
    ///    "error_name": {
    ///      "description": "The error name, for error output",
    ///      "type": "string"
    ///    },
    ///    "error_traceback": {
    ///      "description": "The error traceback lines, for error output",
    ///      "type": "array",
    ///      "items": {
    ///        "type": "string"
    ///      }
    ///    },
    ///    "metadata": {
    ///      "description": "Metadata dictionary, for display_data output",
    ///      "type": "object"
    ///    },
    ///    "stream_name": {
    ///      "description": "The stream name (stdout or stderr), for stream output",
    ///      "type": "string"
    ///    },
    ///    "text": {
    ///      "description": "The text content, for stream output",
    ///      "type": "string"
    ///    },
    ///    "type": {
    ///      "description": "The output message type",
    ///      "type": "string",
    ///      "enum": [
    ///        "stream",
    ///        "display_data",
    ///        "error"
    ///      ]
    ///    }
    ///  }
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ExecuteOutput {
        ///MIME-keyed data, for display_data output
        #[serde(
            default,
            skip_serializing_if = ":: std :: collections :: HashMap::is_empty"
        )]
        pub data: ::std::collections::HashMap<::std::string::String, ::std::string::String>,
        ///The error message, for error output
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub error_message: ::std::option::Option<::std::string::String>,
        ///The error name, for error output
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub error_name: ::std::option::Option<::std::string::String>,
        ///The error traceback lines, for error output
        #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
        pub error_traceback: ::std::vec::Vec<::std::string::String>,
        ///Metadata dictionary, for display_data output
        #[serde(default, skip_serializing_if = "::serde_json::Map::is_empty")]
        pub metadata: ::serde_json::Map<::std::string::String, ::serde_json::Value>,
        ///The stream name (stdout or stderr), for stream output
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub stream_name: ::std::option::Option<::std::string::String>,
        ///The text content, for stream output
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub text: ::std::option::Option<::std::string::String>,
        ///The output message type
        #[serde(rename = "type")]
        pub type_: ExecuteOutputType,
    }
    ///The output message type
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "description": "The output message type",
    ///  "type": "string",
    ///  "enum": [
    ///    "stream",
    ///    "display_data",
    ///    "error"
    ///  ]
    ///}
    /// ```
    /// </details>
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum ExecuteOutputType {
        #[serde(rename = "stream")]
        Stream,
        #[serde(rename = "display_data")]
        DisplayData,
        #[serde(rename = "error")]
        Error,
    }
    impl ::std::fmt::Display for ExecuteOutputType {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Stream => f.write_str("stream"),
                Self::DisplayData => f.write_str("display_data"),
                Self::Error => f.write_str("error"),
            }
        }
    }
    impl ::std::str::FromStr for ExecuteOutputType {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "stream" => Ok(Self::Stream),
                "display_data" => Ok(Self::DisplayData),
                "error" => Ok(Self::Error),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for ExecuteOutputType {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<&::std::string::String> for ExecuteOutputType {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for ExecuteOutputType {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///The result of executing code in a session
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "description": "The result of executing code in a session",
    ///  "type": "object",
    ///  "required": [
    ///    "execution_count",
    ///    "output",
    ///    "status"
    ///  ],
    ///  "properties": {
    ///    "data": {
    ///      "description": "The execution result as a MIME-keyed dictionary (from execute_result), if the execution produced a result",
    ///      "type": "object",
    ///      "additionalProperties": {
    ///        "type": "string"
    ///      }
    ///    },
    ///    "error_message": {
    ///      "description": "The error message, if the execution failed",
    ///      "type": "string"
    ///    },
    ///    "error_name": {
    ///      "description": "The error name, if the execution failed",
    ///      "type": "string"
    ///    },
    ///    "error_traceback": {
    ///      "description": "The error traceback, if the execution failed",
    ///      "type": "array",
    ///      "items": {
    ///        "type": "string"
    ///      }
    ///    },
    ///    "execution_count": {
    ///      "description": "The kernel's execution counter",
    ///      "type": "integer"
    ///    },
    ///    "output": {
    ///      "description": "All output messages produced during execution, in order",
    ///      "type": "array",
    ///      "items": {
    ///        "$ref": "#/components/schemas/executeOutput"
    ///      }
    ///    },
    ///    "status": {
    ///      "description": "Whether the execution succeeded or errored",
    ///      "type": "string",
    ///      "enum": [
    ///        "ok",
    ///        "error"
    ///      ]
    ///    }
    ///  }
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ExecuteReply {
        ///The execution result as a MIME-keyed dictionary (from execute_result), if the execution produced a result
        #[serde(
            default,
            skip_serializing_if = ":: std :: collections :: HashMap::is_empty"
        )]
        pub data: ::std::collections::HashMap<::std::string::String, ::std::string::String>,
        ///The error message, if the execution failed
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub error_message: ::std::option::Option<::std::string::String>,
        ///The error name, if the execution failed
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub error_name: ::std::option::Option<::std::string::String>,
        ///The error traceback, if the execution failed
        #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
        pub error_traceback: ::std::vec::Vec<::std::string::String>,
        ///The kernel's execution counter
        pub execution_count: i64,
        ///All output messages produced during execution, in order
        pub output: ::std::vec::Vec<ExecuteOutput>,
        ///Whether the execution succeeded or errored
        pub status: ExecuteReplyStatus,
    }
    ///Whether the execution succeeded or errored
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "description": "Whether the execution succeeded or errored",
    ///  "type": "string",
    ///  "enum": [
    ///    "ok",
    ///    "error"
    ///  ]
    ///}
    /// ```
    /// </details>
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum ExecuteReplyStatus {
        #[serde(rename = "ok")]
        Ok,
        #[serde(rename = "error")]
        Error,
    }
    impl ::std::fmt::Display for ExecuteReplyStatus {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Ok => f.write_str("ok"),
                Self::Error => f.write_str("error"),
            }
        }
    }
    impl ::std::str::FromStr for ExecuteReplyStatus {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "ok" => Ok(Self::Ok),
                "error" => Ok(Self::Error),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for ExecuteReplyStatus {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<&::std::string::String> for ExecuteReplyStatus {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for ExecuteReplyStatus {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///A request to execute code in a session
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "description": "A request to execute code in a session",
    ///  "type": "object",
    ///  "required": [
    ///    "code"
    ///  ],
    ///  "properties": {
    ///    "code": {
    ///      "description": "The code to execute",
    ///      "type": "string"
    ///    },
    ///    "silent": {
    ///      "description": "If true, signals the kernel to execute quietly: no broadcast on iopub, no execute_result, and the execution_count is not incremented. Defaults to false.",
    ///      "default": false,
    ///      "type": "boolean"
    ///    },
    ///    "stop_on_error": {
    ///      "description": "If true (default), abort the execution queue on error. If false, queued execute requests will still be processed even if this one fails.",
    ///      "default": true,
    ///      "type": "boolean"
    ///    },
    ///    "store_history": {
    ///      "description": "If true (default), the code is stored in the kernel's history. Set to false for throwaway executions.",
    ///      "default": true,
    ///      "type": "boolean"
    ///    },
    ///    "timeout_seconds": {
    ///      "description": "Maximum number of seconds to wait for execution to complete. If not specified, the request will block indefinitely until execution finishes.",
    ///      "type": "integer"
    ///    }
    ///  }
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ExecuteRequest {
        ///The code to execute
        pub code: ::std::string::String,
        ///If true, signals the kernel to execute quietly: no broadcast on iopub, no execute_result, and the execution_count is not incremented. Defaults to false.
        #[serde(default)]
        pub silent: bool,
        ///If true (default), abort the execution queue on error. If false, queued execute requests will still be processed even if this one fails.
        #[serde(default = "defaults::default_bool::<true>")]
        pub stop_on_error: bool,
        ///If true (default), the code is stored in the kernel's history. Set to false for throwaway executions.
        #[serde(default = "defaults::default_bool::<true>")]
        pub store_history: bool,
        ///Maximum number of seconds to wait for execution to complete. If not specified, the request will block indefinitely until execution finishes.
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub timeout_seconds: ::std::option::Option<i64>,
    }
    ///The execution queue for a session
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "description": "The execution queue for a session",
    ///  "type": "object",
    ///  "required": [
    ///    "length",
    ///    "pending"
    ///  ],
    ///  "properties": {
    ///    "active": {
    ///      "description": "The execution request currently being evaluated, if any",
    ///      "type": "object"
    ///    },
    ///    "length": {
    ///      "description": "The number of items in the pending queue",
    ///      "type": "integer"
    ///    },
    ///    "pending": {
    ///      "description": "The queue of pending execution requests",
    ///      "type": "array",
    ///      "items": {
    ///        "type": "object"
    ///      }
    ///    }
    ///  }
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ExecutionQueue {
        ///The execution request currently being evaluated, if any
        #[serde(default, skip_serializing_if = "::serde_json::Map::is_empty")]
        pub active: ::serde_json::Map<::std::string::String, ::serde_json::Value>,
        ///The number of items in the pending queue
        pub length: i64,
        ///The queue of pending execution requests
        pub pending: ::std::vec::Vec<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    ///The mechansim for interrupting the session
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "description": "The mechansim for interrupting the session",
    ///  "type": "string",
    ///  "enum": [
    ///    "signal",
    ///    "message"
    ///  ]
    ///}
    /// ```
    /// </details>
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum InterruptMode {
        #[serde(rename = "signal")]
        Signal,
        #[serde(rename = "message")]
        Message,
    }
    impl ::std::fmt::Display for InterruptMode {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Signal => f.write_str("signal"),
                Self::Message => f.write_str("message"),
            }
        }
    }
    impl ::std::str::FromStr for InterruptMode {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "signal" => Ok(Self::Signal),
                "message" => Ok(Self::Message),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for InterruptMode {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<&::std::string::String> for InterruptMode {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for InterruptMode {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`NewSession`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "object",
    ///  "required": [
    ///    "argv",
    ///    "continuation_prompt",
    ///    "display_name",
    ///    "env",
    ///    "input_prompt",
    ///    "interrupt_mode",
    ///    "language",
    ///    "session_id",
    ///    "session_mode",
    ///    "startup_environment",
    ///    "username",
    ///    "working_directory"
    ///  ],
    ///  "properties": {
    ///    "argv": {
    ///      "description": "The program and command-line parameters for the session",
    ///      "type": "array",
    ///      "items": {
    ///        "type": "string"
    ///      }
    ///    },
    ///    "connection_timeout": {
    ///      "description": "The number of seconds to wait for a connection to the session's ZeroMQ sockets before timing out",
    ///      "default": 30,
    ///      "type": "integer"
    ///    },
    ///    "continuation_prompt": {
    ///      "description": "The text to use to prompt for input continuations",
    ///      "type": "string"
    ///    },
    ///    "display_name": {
    ///      "description": "A human-readable name for the session",
    ///      "type": "string"
    ///    },
    ///    "env": {
    ///      "$ref": "#/components/schemas/envVarActions"
    ///    },
    ///    "input_prompt": {
    ///      "description": "The text to use to prompt for input",
    ///      "type": "string"
    ///    },
    ///    "interrupt_mode": {
    ///      "$ref": "#/components/schemas/interrupt_mode"
    ///    },
    ///    "language": {
    ///      "description": "The interpreter language",
    ///      "type": "string"
    ///    },
    ///    "notebook_uri": {
    ///      "description": "For notebook sessions, the URI of the notebook file",
    ///      "type": "string"
    ///    },
    ///    "protocol_version": {
    ///      "description": "The Jupyter protocol version supported by the underlying kernel",
    ///      "default": "5.3",
    ///      "type": "string"
    ///    },
    ///    "session_id": {
    ///      "description": "A unique identifier for the session",
    ///      "type": "string"
    ///    },
    ///    "session_mode": {
    ///      "$ref": "#/components/schemas/sessionMode"
    ///    },
    ///    "startup_environment": {
    ///      "$ref": "#/components/schemas/startupEnvironment"
    ///    },
    ///    "startup_environment_arg": {
    ///      "description": "The command or script to run before starting the session",
    ///      "type": "string"
    ///    },
    ///    "username": {
    ///      "description": "The username of the user who owns the session",
    ///      "type": "string"
    ///    },
    ///    "working_directory": {
    ///      "description": "The working directory in which to start the session.",
    ///      "type": "string"
    ///    }
    ///  }
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct NewSession {
        ///The program and command-line parameters for the session
        pub argv: ::std::vec::Vec<::std::string::String>,
        ///The number of seconds to wait for a connection to the session's ZeroMQ sockets before timing out
        #[serde(default = "defaults::default_u64::<i64, 30>")]
        pub connection_timeout: i64,
        ///The text to use to prompt for input continuations
        pub continuation_prompt: ::std::string::String,
        ///A human-readable name for the session
        pub display_name: ::std::string::String,
        pub env: EnvVarActions,
        ///The text to use to prompt for input
        pub input_prompt: ::std::string::String,
        pub interrupt_mode: InterruptMode,
        ///The interpreter language
        pub language: ::std::string::String,
        ///For notebook sessions, the URI of the notebook file
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub notebook_uri: ::std::option::Option<::std::string::String>,
        ///The Jupyter protocol version supported by the underlying kernel
        #[serde(default = "defaults::new_session_protocol_version")]
        pub protocol_version: ::std::string::String,
        ///A unique identifier for the session
        pub session_id: ::std::string::String,
        pub session_mode: SessionMode,
        pub startup_environment: StartupEnvironment,
        ///The command or script to run before starting the session
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub startup_environment_arg: ::std::option::Option<::std::string::String>,
        ///The username of the user who owns the session
        pub username: ::std::string::String,
        ///The working directory in which to start the session.
        pub working_directory: ::std::string::String,
    }
    ///`NewSessionResponse`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "object",
    ///  "required": [
    ///    "session_id"
    ///  ],
    ///  "properties": {
    ///    "session_id": {
    ///      "description": "A unique identifier for the session",
    ///      "type": "string"
    ///    }
    ///  }
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct NewSessionResponse {
        ///A unique identifier for the session
        pub session_id: ::std::string::String,
    }
    ///`ResourceUsage`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "object",
    ///  "required": [
    ///    "cpu_percent",
    ///    "memory_bytes",
    ///    "sampling_period_ms",
    ///    "thread_count",
    ///    "timestamp"
    ///  ],
    ///  "properties": {
    ///    "cpu_percent": {
    ///      "description": "The percentage of CPU used by the kernel process and its child processes",
    ///      "type": "integer",
    ///      "format": "int64"
    ///    },
    ///    "memory_bytes": {
    ///      "description": "The amount of memory used by the kernel process and all of its child processes in bytes",
    ///      "type": "integer",
    ///      "format": "int64"
    ///    },
    ///    "sampling_period_ms": {
    ///      "description": "The sampling period in milliseconds over which the resource usage was measured",
    ///      "type": "integer",
    ///      "format": "int64"
    ///    },
    ///    "thread_count": {
    ///      "description": "The total number of threads used by the kernel process and its child processes (Linux only)",
    ///      "type": "integer",
    ///      "format": "int64"
    ///    },
    ///    "timestamp": {
    ///      "description": "A Unix timestamp in milliseconds indicating when the resource usage was sampled",
    ///      "type": "integer",
    ///      "format": "int64"
    ///    }
    ///  }
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ResourceUsage {
        ///The percentage of CPU used by the kernel process and its child processes
        pub cpu_percent: i64,
        ///The amount of memory used by the kernel process and all of its child processes in bytes
        pub memory_bytes: i64,
        ///The sampling period in milliseconds over which the resource usage was measured
        pub sampling_period_ms: i64,
        ///The total number of threads used by the kernel process and its child processes (Linux only)
        pub thread_count: i64,
        ///A Unix timestamp in milliseconds indicating when the resource usage was sampled
        pub timestamp: i64,
    }
    ///`RestartSession`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "object",
    ///  "properties": {
    ///    "env": {
    ///      "$ref": "#/components/schemas/envVarActions"
    ///    },
    ///    "working_directory": {
    ///      "description": "The desired working directory for the session after restart, if different from the session's working directory at startup",
    ///      "type": "string"
    ///    }
    ///  }
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct RestartSession {
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub env: ::std::option::Option<EnvVarActions>,
        ///The desired working directory for the session after restart, if different from the session's working directory at startup
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub working_directory: ::std::option::Option<::std::string::String>,
    }
    impl ::std::default::Default for RestartSession {
        fn default() -> Self {
            Self {
                env: Default::default(),
                working_directory: Default::default(),
            }
        }
    }
    ///`ServerConfiguration`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "object",
    ///  "properties": {
    ///    "idle_shutdown_hours": {
    ///      "description": "The number of hours the server will wait before shutting down idle sessions (-1 if idle shutdown is disabled)",
    ///      "type": "integer"
    ///    },
    ///    "log_level": {
    ///      "description": "The current log level",
    ///      "type": "string",
    ///      "enum": [
    ///        "trace",
    ///        "debug",
    ///        "info",
    ///        "warn",
    ///        "error"
    ///      ]
    ///    },
    ///    "resource_sample_interval_ms": {
    ///      "description": "The interval in milliseconds at which resource usage is sampled. A value of 0 disables resource usage sampling.",
    ///      "type": "integer"
    ///    }
    ///  }
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ServerConfiguration {
        ///The number of hours the server will wait before shutting down idle sessions (-1 if idle shutdown is disabled)
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub idle_shutdown_hours: ::std::option::Option<i64>,
        ///The current log level
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub log_level: ::std::option::Option<ServerConfigurationLogLevel>,
        ///The interval in milliseconds at which resource usage is sampled. A value of 0 disables resource usage sampling.
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub resource_sample_interval_ms: ::std::option::Option<i64>,
    }
    impl ::std::default::Default for ServerConfiguration {
        fn default() -> Self {
            Self {
                idle_shutdown_hours: Default::default(),
                log_level: Default::default(),
                resource_sample_interval_ms: Default::default(),
            }
        }
    }
    ///The current log level
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "description": "The current log level",
    ///  "type": "string",
    ///  "enum": [
    ///    "trace",
    ///    "debug",
    ///    "info",
    ///    "warn",
    ///    "error"
    ///  ]
    ///}
    /// ```
    /// </details>
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum ServerConfigurationLogLevel {
        #[serde(rename = "trace")]
        Trace,
        #[serde(rename = "debug")]
        Debug,
        #[serde(rename = "info")]
        Info,
        #[serde(rename = "warn")]
        Warn,
        #[serde(rename = "error")]
        Error,
    }
    impl ::std::fmt::Display for ServerConfigurationLogLevel {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Trace => f.write_str("trace"),
                Self::Debug => f.write_str("debug"),
                Self::Info => f.write_str("info"),
                Self::Warn => f.write_str("warn"),
                Self::Error => f.write_str("error"),
            }
        }
    }
    impl ::std::str::FromStr for ServerConfigurationLogLevel {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "trace" => Ok(Self::Trace),
                "debug" => Ok(Self::Debug),
                "info" => Ok(Self::Info),
                "warn" => Ok(Self::Warn),
                "error" => Ok(Self::Error),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for ServerConfigurationLogLevel {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<&::std::string::String> for ServerConfigurationLogLevel {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for ServerConfigurationLogLevel {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`ServerStatus`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "object",
    ///  "required": [
    ///    "active",
    ///    "busy",
    ///    "busy_seconds",
    ///    "idle_seconds",
    ///    "process_id",
    ///    "sessions",
    ///    "started",
    ///    "uptime_seconds",
    ///    "version"
    ///  ],
    ///  "properties": {
    ///    "active": {
    ///      "type": "integer"
    ///    },
    ///    "busy": {
    ///      "type": "boolean"
    ///    },
    ///    "busy_seconds": {
    ///      "description": "The number of seconds any session has been busy, or 0 if all sessions are idle",
    ///      "type": "integer"
    ///    },
    ///    "idle_seconds": {
    ///      "description": "The number of seconds all sessions have been idle, or 0 if any session is busy",
    ///      "type": "integer"
    ///    },
    ///    "process_id": {
    ///      "description": "The server's operating system process identifier",
    ///      "type": "integer"
    ///    },
    ///    "sessions": {
    ///      "type": "integer"
    ///    },
    ///    "started": {
    ///      "description": "An ISO 8601 timestamp of when the server was started",
    ///      "type": "string",
    ///      "format": "date-time"
    ///    },
    ///    "uptime_seconds": {
    ///      "description": "The number of seconds the server has been running",
    ///      "type": "integer"
    ///    },
    ///    "version": {
    ///      "description": "The version of the server",
    ///      "type": "string"
    ///    }
    ///  }
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ServerStatus {
        pub active: i64,
        pub busy: bool,
        ///The number of seconds any session has been busy, or 0 if all sessions are idle
        pub busy_seconds: i64,
        ///The number of seconds all sessions have been idle, or 0 if any session is busy
        pub idle_seconds: i64,
        ///The server's operating system process identifier
        pub process_id: i64,
        pub sessions: i64,
        ///An ISO 8601 timestamp of when the server was started
        pub started: ::chrono::DateTime<::chrono::offset::Utc>,
        ///The number of seconds the server has been running
        pub uptime_seconds: i64,
        ///The version of the server
        pub version: ::std::string::String,
    }
    ///`SessionList`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "object",
    ///  "required": [
    ///    "sessions",
    ///    "total"
    ///  ],
    ///  "properties": {
    ///    "sessions": {
    ///      "type": "array",
    ///      "items": {
    ///        "$ref": "#/components/schemas/activeSession"
    ///      }
    ///    },
    ///    "total": {
    ///      "type": "integer"
    ///    }
    ///  }
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct SessionList {
        pub sessions: ::std::vec::Vec<ActiveSession>,
        pub total: i64,
    }
    ///The mode in which the session is running
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "description": "The mode in which the session is running",
    ///  "type": "string",
    ///  "enum": [
    ///    "console",
    ///    "notebook",
    ///    "background"
    ///  ]
    ///}
    /// ```
    /// </details>
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum SessionMode {
        #[serde(rename = "console")]
        Console,
        #[serde(rename = "notebook")]
        Notebook,
        #[serde(rename = "background")]
        Background,
    }
    impl ::std::fmt::Display for SessionMode {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Console => f.write_str("console"),
                Self::Notebook => f.write_str("notebook"),
                Self::Background => f.write_str("background"),
            }
        }
    }
    impl ::std::str::FromStr for SessionMode {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "console" => Ok(Self::Console),
                "notebook" => Ok(Self::Notebook),
                "background" => Ok(Self::Background),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for SessionMode {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<&::std::string::String> for SessionMode {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for SessionMode {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///The kernel's startup environment: 'none' for normal startup, 'shell' for a login shell, 'command' for a preflight command, 'script' to run a script. Only relevant on POSIX-like systems.
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "description": "The kernel's startup environment: 'none' for normal startup, 'shell' for a login shell, 'command' for a preflight command, 'script' to run a script. Only relevant on POSIX-like systems.",
    ///  "type": "string",
    ///  "enum": [
    ///    "none",
    ///    "shell",
    ///    "command",
    ///    "script"
    ///  ]
    ///}
    /// ```
    /// </details>
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum StartupEnvironment {
        #[serde(rename = "none")]
        None,
        #[serde(rename = "shell")]
        Shell,
        #[serde(rename = "command")]
        Command,
        #[serde(rename = "script")]
        Script,
    }
    impl ::std::fmt::Display for StartupEnvironment {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::None => f.write_str("none"),
                Self::Shell => f.write_str("shell"),
                Self::Command => f.write_str("command"),
                Self::Script => f.write_str("script"),
            }
        }
    }
    impl ::std::str::FromStr for StartupEnvironment {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "none" => Ok(Self::None),
                "shell" => Ok(Self::Shell),
                "command" => Ok(Self::Command),
                "script" => Ok(Self::Script),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for StartupEnvironment {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<&::std::string::String> for StartupEnvironment {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for StartupEnvironment {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`StartupError`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "object",
    ///  "required": [
    ///    "error"
    ///  ],
    ///  "properties": {
    ///    "error": {
    ///      "$ref": "#/components/schemas/error"
    ///    },
    ///    "exit_code": {
    ///      "description": "The exit code of the process, if it exited",
    ///      "type": "integer"
    ///    },
    ///    "output": {
    ///      "description": "The output of the process (combined stdout and stderr) emitted during startup, if any",
    ///      "type": "string"
    ///    }
    ///  }
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct StartupError {
        pub error: Error,
        ///The exit code of the process, if it exited
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub exit_code: ::std::option::Option<i64>,
        ///The output of the process (combined stdout and stderr) emitted during startup, if any
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub output: ::std::option::Option<::std::string::String>,
    }
    ///The status of the session
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "description": "The status of the session",
    ///  "type": "string",
    ///  "enum": [
    ///    "uninitialized",
    ///    "starting",
    ///    "ready",
    ///    "idle",
    ///    "busy",
    ///    "offline",
    ///    "exited"
    ///  ]
    ///}
    /// ```
    /// </details>
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum Status {
        #[serde(rename = "uninitialized")]
        Uninitialized,
        #[serde(rename = "starting")]
        Starting,
        #[serde(rename = "ready")]
        Ready,
        #[serde(rename = "idle")]
        Idle,
        #[serde(rename = "busy")]
        Busy,
        #[serde(rename = "offline")]
        Offline,
        #[serde(rename = "exited")]
        Exited,
    }
    impl ::std::fmt::Display for Status {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Uninitialized => f.write_str("uninitialized"),
                Self::Starting => f.write_str("starting"),
                Self::Ready => f.write_str("ready"),
                Self::Idle => f.write_str("idle"),
                Self::Busy => f.write_str("busy"),
                Self::Offline => f.write_str("offline"),
                Self::Exited => f.write_str("exited"),
            }
        }
    }
    impl ::std::str::FromStr for Status {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "uninitialized" => Ok(Self::Uninitialized),
                "starting" => Ok(Self::Starting),
                "ready" => Ok(Self::Ready),
                "idle" => Ok(Self::Idle),
                "busy" => Ok(Self::Busy),
                "offline" => Ok(Self::Offline),
                "exited" => Ok(Self::Exited),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for Status {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<&::std::string::String> for Status {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for Status {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`VarAction`
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "type": "object",
    ///  "required": [
    ///    "action",
    ///    "name",
    ///    "value"
    ///  ],
    ///  "properties": {
    ///    "action": {
    ///      "$ref": "#/components/schemas/varActionType"
    ///    },
    ///    "name": {
    ///      "description": "The name of the variable to act on",
    ///      "type": "string"
    ///    },
    ///    "value": {
    ///      "description": "The value to replace, append, or prepend",
    ///      "type": "string"
    ///    }
    ///  }
    ///}
    /// ```
    /// </details>
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct VarAction {
        pub action: VarActionType,
        ///The name of the variable to act on
        pub name: ::std::string::String,
        ///The value to replace, append, or prepend
        pub value: ::std::string::String,
    }
    ///The type of action to perform on the environment variable
    ///
    /// <details><summary>JSON schema</summary>
    ///
    /// ```json
    ///{
    ///  "description": "The type of action to perform on the environment variable",
    ///  "type": "string",
    ///  "enum": [
    ///    "replace",
    ///    "append",
    ///    "prepend"
    ///  ]
    ///}
    /// ```
    /// </details>
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum VarActionType {
        #[serde(rename = "replace")]
        Replace,
        #[serde(rename = "append")]
        Append,
        #[serde(rename = "prepend")]
        Prepend,
    }
    impl ::std::fmt::Display for VarActionType {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Replace => f.write_str("replace"),
                Self::Append => f.write_str("append"),
                Self::Prepend => f.write_str("prepend"),
            }
        }
    }
    impl ::std::str::FromStr for VarActionType {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "replace" => Ok(Self::Replace),
                "append" => Ok(Self::Append),
                "prepend" => Ok(Self::Prepend),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for VarActionType {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<&::std::string::String> for VarActionType {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for VarActionType {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    /// Generation of default values for serde.
    pub mod defaults {
        pub(super) fn default_bool<const V: bool>() -> bool {
            V
        }
        pub(super) fn default_u64<T, const V: u64>() -> T
        where
            T: ::std::convert::TryFrom<u64>,
            <T as ::std::convert::TryFrom<u64>>::Error: ::std::fmt::Debug,
        {
            T::try_from(V).unwrap()
        }
        pub(super) fn new_session_protocol_version() -> ::std::string::String {
            "5.3".to_string()
        }
    }
}
#[derive(Clone, Debug)]
/**Client for Kallichore API

Kallichore is a Jupyter kernel gateway and supervisor

Version: 1.0.0*/
pub struct Client {
    pub(crate) baseurl: String,
    pub(crate) client: reqwest::Client,
}
impl Client {
    /// Create a new client.
    ///
    /// `baseurl` is the base URL provided to the internal
    /// `reqwest::Client`, and should include a scheme and hostname,
    /// as well as port and a path stem if applicable.
    pub fn new(baseurl: &str) -> Self {
        #[cfg(not(target_arch = "wasm32"))]
        let client = {
            let dur = ::std::time::Duration::from_secs(15u64);
            reqwest::ClientBuilder::new()
                .connect_timeout(dur)
                .timeout(dur)
        };
        #[cfg(target_arch = "wasm32")]
        let client = reqwest::ClientBuilder::new();
        Self::new_with_client(baseurl, client.build().unwrap())
    }
    /// Construct a new client with an existing `reqwest::Client`,
    /// allowing more control over its configuration.
    ///
    /// `baseurl` is the base URL provided to the internal
    /// `reqwest::Client`, and should include a scheme and hostname,
    /// as well as port and a path stem if applicable.
    pub fn new_with_client(baseurl: &str, client: reqwest::Client) -> Self {
        Self {
            baseurl: baseurl.to_string(),
            client,
        }
    }
}
impl ClientInfo<()> for Client {
    fn api_version() -> &'static str {
        "1.0.0"
    }
    fn baseurl(&self) -> &str {
        self.baseurl.as_str()
    }
    fn client(&self) -> &reqwest::Client {
        &self.client
    }
    fn inner(&self) -> &() {
        &()
    }
}
impl ClientHooks<()> for &Client {}
#[allow(clippy::all)]
impl Client {
    /**Notify the server that a client is connected

    Sends a `POST` request to `/client_heartbeat`

    */
    pub async fn client_heartbeat<'a>(
        &'a self,
        body: &'a types::ClientHeartbeat,
    ) -> Result<ResponseValue<::serde_json::Value>, Error<()>> {
        let url = format!("{}/client_heartbeat", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "client_heartbeat",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Get the server configuration

    Sends a `GET` request to `/server_configuration`

    */
    pub async fn get_server_configuration<'a>(
        &'a self,
    ) -> Result<ResponseValue<types::ServerConfiguration>, Error<()>> {
        let url = format!("{}/server_configuration", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "get_server_configuration",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Change the server configuration

    Sends a `POST` request to `/server_configuration`

    */
    pub async fn set_server_configuration<'a>(
        &'a self,
        body: &'a types::ServerConfiguration,
    ) -> Result<ResponseValue<::serde_json::Value>, Error<()>> {
        let url = format!("{}/server_configuration", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "set_server_configuration",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**List active sessions

    Sends a `GET` request to `/sessions`

    */
    pub async fn list_sessions<'a>(
        &'a self,
    ) -> Result<ResponseValue<types::SessionList>, Error<()>> {
        let url = format!("{}/sessions", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "list_sessions",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Create a new session

    Sends a `PUT` request to `/sessions`

    */
    pub async fn new_session<'a>(
        &'a self,
        body: &'a types::NewSession,
    ) -> Result<ResponseValue<types::NewSessionResponse>, Error<()>> {
        let url = format!("{}/sessions", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .put(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "new_session",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Get session details

    Sends a `GET` request to `/sessions/{session_id}`

    */
    pub async fn get_session<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Result<ResponseValue<types::ActiveSession>, Error<()>> {
        let url = format!(
            "{}/sessions/{}",
            self.baseurl,
            encode_path(&session_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "get_session",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Delete session

    Sends a `DELETE` request to `/sessions/{session_id}`

    */
    pub async fn delete_session<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Result<ResponseValue<::serde_json::Value>, Error<()>> {
        let url = format!(
            "{}/sessions/{}",
            self.baseurl,
            encode_path(&session_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .delete(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "delete_session",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Adopt an existing session

    Sends a `PUT` request to `/sessions/{session_id}/adopt`

    */
    pub async fn adopt_session<'a>(
        &'a self,
        session_id: &'a str,
        body: &'a types::ConnectionInfo,
    ) -> Result<ResponseValue<::serde_json::Value>, Error<()>> {
        let url = format!(
            "{}/sessions/{}/adopt",
            self.baseurl,
            encode_path(&session_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .put(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "adopt_session",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Upgrade to a WebSocket or domain socket for channel communication

    Sends a `GET` request to `/sessions/{session_id}/channels`

    */
    pub async fn channels_upgrade<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Result<ResponseValue<::std::string::String>, Error<()>> {
        let url = format!(
            "{}/sessions/{}/channels",
            self.baseurl,
            encode_path(&session_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "channels_upgrade",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Get Jupyter connection information for the session

    Sends a `GET` request to `/sessions/{session_id}/connection_info`

    */
    pub async fn connection_info<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Result<ResponseValue<types::ConnectionInfo>, Error<()>> {
        let url = format!(
            "{}/sessions/{}/connection_info",
            self.baseurl,
            encode_path(&session_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "connection_info",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Execute code and return results

    Sends a `POST` request to `/sessions/{session_id}/execute`

    */
    pub async fn execute_code<'a>(
        &'a self,
        session_id: &'a str,
        body: &'a types::ExecuteRequest,
    ) -> Result<ResponseValue<types::ExecuteReply>, Error<()>> {
        let url = format!(
            "{}/sessions/{}/execute",
            self.baseurl,
            encode_path(&session_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "execute_code",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Interrupt session

    Sends a `POST` request to `/sessions/{session_id}/interrupt`

    */
    pub async fn interrupt_session<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Result<ResponseValue<::serde_json::Value>, Error<()>> {
        let url = format!(
            "{}/sessions/{}/interrupt",
            self.baseurl,
            encode_path(&session_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "interrupt_session",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Force quit session

    Sends a `POST` request to `/sessions/{session_id}/kill`

    */
    pub async fn kill_session<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Result<ResponseValue<::serde_json::Value>, Error<()>> {
        let url = format!(
            "{}/sessions/{}/kill",
            self.baseurl,
            encode_path(&session_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "kill_session",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Restart a session

    Sends a `POST` request to `/sessions/{session_id}/restart`

    */
    pub async fn restart_session<'a>(
        &'a self,
        session_id: &'a str,
        body: &'a types::RestartSession,
    ) -> Result<ResponseValue<::serde_json::Value>, Error<()>> {
        let url = format!(
            "{}/sessions/{}/restart",
            self.baseurl,
            encode_path(&session_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "restart_session",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Start a session

    Sends a `POST` request to `/sessions/{session_id}/start`

    */
    pub async fn start_session<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Result<ResponseValue<::serde_json::Value>, Error<()>> {
        let url = format!(
            "{}/sessions/{}/start",
            self.baseurl,
            encode_path(&session_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "start_session",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Shut down all sessions and the server itself

    Sends a `POST` request to `/shutdown`

    */
    pub async fn shutdown_server<'a>(
        &'a self,
    ) -> Result<ResponseValue<::serde_json::Value>, Error<()>> {
        let url = format!("{}/shutdown", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "shutdown_server",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Get server status and information

    Sends a `GET` request to `/status`

    */
    pub async fn server_status<'a>(
        &'a self,
    ) -> Result<ResponseValue<types::ServerStatus>, Error<()>> {
        let url = format!("{}/status", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "server_status",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
}
/// Items consumers will typically use such as the Client.
pub mod prelude {
    #[allow(unused_imports)]
    pub use super::Client;
}
